### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by ldemattos** [ldemattos/readPL4#3]
readPL4 must have one python3 version since python2 is officially decommissioned.

**Comment by pdb5627** [comment]
#4 I created a pull request with the changes needed for Python 3 compatibility

**Comment by ldemattos** [comment]
Dear @pdb5627 ,

First of all, thanks for your contribution!

I just merged your python3 branch. I just pushed to the new files readPL4_py3.py and lib_readPL4_py3.py once I still need the legacy code in python2.

I did that also because I have advanced a little bit the code on the branch issue_#1 and perhaps there will be few conflicts between the actual master branch and the issue_#1 branch.

Again, thanks for your contribution!
